version: '3.8'

services:
  # Example bot instance 1 - Company Bot
  company-bot:
    build: .
    container_name: item-bot-company
    restart: unless-stopped
    environment:
      - BOT_NAME=company-bot
      - DATABASE_PATH=/app/data/company-resources.db
      - LOG_FILE=/app/logs/company-bot.log
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - COMPANY_BOT_TOKEN=${COMPANY_BOT_TOKEN}
      - COMPANY_ADMIN_1=${COMPANY_ADMIN_1}
    volumes:
      - ./config/company-config.py:/app/config.py:ro
      - company-bot-data:/app/data
      - company-bot-logs:/app/logs
    networks:
      - bot-network
    labels:
      - "bot.instance=company"
      - "bot.type=item-manager"

volumes:
  company-bot-data:
    driver: local
  company-bot-logs:
    driver: local

networks:
  bot-network:
    driver: bridge
